### ISSUE TITLE
Import from sd card

### ISSUE THREAD

**Issue by G-Ray** [flathub/org.gnome.Shotwell#11]
The sandbox seem restrictive (only downloads and pictures folders).

Would it be possible to access to an SD Card to import pictures ?

**Comment by phako** [comment]
Odd. That used to work

**Comment by phako** [comment]
You should be able to access it from File -> Import from Directory

**Comment by G-Ray** [comment]
Unfortunately I confirm that I can't access to my sd card using `File -> Import from folder`
