### ISSUE TITLE
Update to Shotwell 0.31.0

### ISSUE THREAD

**Issue by logix2** [flathub/org.gnome.Shotwell#12]
Shotwell 0.31.0 was released about 2 weeks ago (https://gitlab.gnome.org/GNOME/shotwell/blob/master/NEWS) with some major improvements (https://gitlab.gnome.org/GNOME/shotwell/blob/master/NEWS). Could you please update Flathub with the latest version? Thanks!

**Comment by phako** [comment]
No. That is an unstable version. There is an unstable/experimental flatpak channel in the repository itself, if you like.

**Comment by proletarius101** [comment]
@phako So has it stable now?

**Comment by phako** [comment]
No.

**Comment by logix2** [comment]
Just give up on Shotwell and use something else, like the rest of us.

**Comment by phako** [comment]
Look, it's just me. I'm doing the development, the releases, the user support. I have a day job to pay me my rent. Feel free to join in.
