### ISSUE TITLE
Set as Desktop Slideshow doesn't work

### ISSUE THREAD

**Issue by FakeShemp** [flathub/org.gnome.Shotwell#35]
This option does not work within the flatpak sandbox. This is expected with the available portals, but wouldn't it make sense to then be able to save the generated xml at an arbitrary place instead?

**Comment by phako** [comment]
There should be a portal for this, if I understand https://github.com/flatpak/xdg-desktop-portal/issues/335 correctly

**Comment by jkemp814** [comment]
I am having the same problem on Fedora Linux 37 Silverblue. Using the Flatpak.

**Comment by phako** [comment]
I have fixed this upstream and it will be included in the next release, modulo the issues in this bug here: https://github.com/flatpak/xdg-desktop-portal-gtk/issues/404 and you will have to log out and in again, but that is nothing I can fix in Shotwell.
