### ISSUE TITLE
Uptate to new version

### ISSUE THREAD

**Issue by libreajans** [flathub/org.gnome.Shotwell#36]
Hi 

There is a new version for Shotwell with some fixes.

Could you update flatpak to the new version?

https://gitlab.gnome.org/GNOME/shotwell/-/commit/0303d8d30d5dcff4e9c608434a4af2d5faa2ef92

Thanks.

**Comment by phako** [comment]
A new new version is immanent (and contains an important fix) so I was going to skip .15

**Comment by barthalion** [comment]
I pushed out a branch that also bumps the runtime and deps, see https://github.com/flathub/org.gnome.Shotwell/tree/update-to-42. I can either open a pull request or just leave it be as a starting point for the next release.

**Comment by phako** [comment]
I have just pushed out 0.30.16
sha265: c9882cfbdad303cb8161b149acbb4c617fbe7ca9f6ab6e22d174e2447e7518fa
md5: 57fdf3d2f5cb30c070710eabebbfea16

so if you update to that and make a PR - much appreciated!

**Comment by barthalion** [comment]
Done: https://github.com/flathub/org.gnome.Shotwell/pull/37
