### ISSUE TITLE
Update to runtime

### ISSUE THREAD

**Issue by sukahiroaki** [flathub/org.gnome.Shotwell#41]
Flatpak output:

Info: runtime org.gnome.Platform branch 42 is end-of-life, with reason:
   The GNOME 42 runtime is no longer supported as of March 21, 2023. Please ask your application developer to migrate to a supported platform.
Info: applications using this runtime:
   org.gnome.Shotwell

**Comment by phako** [comment]
Ah. The problem was that the 43 runtime does not come with webkitgtk 4.0 and libsoup2. that's slightly annoying.

**Comment by phako** [comment]
Will be done once shotwell 0.32 is releaed (end of april)
