### ISSUE TITLE
'Write strategy: Intrusive' when trying to delete item

### ISSUE THREAD

**Issue by ghost** [flathub/org.gnome.Shotwell#46]
My library points to `/run/user/`.

> Shotwell
> Unable to send file IMG_1274.png,
> GDBus.Error:org.freedesktop.portal.Error.InvalidArgument: Invalid attachment fd passed

> `L 2 2023-04-29 17:27:59 [MSG] Write strategy: Intrusive`

**Comment by phako** [comment]
That has nothing to do with the issue. I have filed https://github.com/flatpak/xdg-desktop-portal/issues/1012 - Not sure if I am using it wrong or if it is a bug in the portal
