### ISSUE TITLE
External editor is not selectable.

### ISSUE THREAD

**Issue by achimfrase** [flathub/org.gnome.Shotwell#8]
Hi,
I can't choose an external editor in the flatpak-version of shotwell.
I would like to choose gimp for example.

**Comment by nedrichards** [comment]
This is more of an issue for https://github.com/flatpak/flatpak or https://github.com/flatpak/xdg-desktop-portal to make sure there's a safe API for applications to do zero knowledge 'share intent' style computing between them. And then a different ticket for Shotwell upstream to add that.

As it is, flatpak containers are designed not to expose the rest of your system to an application.
